service: test-code
configValidationMode: warn # NOTE: To account for http.authorizer.type: CUSTOM. Default after v3 is 'error'
variablesResolutionMode: 20210326
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  stage: ${opt:stage}
  region: ${opt:region}
  tracing:
    lambda: false
  versionFunctions: false
  logRetentionInDays: ${self:custom.logRetention}
  deploymentBucket:
    name: amanda-test-bucket
  iam:
    role:
      statements: ${file(serverless/resources/iamRoleStatements.yml)}
  environment: ${file(serverless/config/environment.yml)}
custom: ${file(serverless/config/custom_${self:provider.stage}.yml)}
functions: ${file(serverless/resources/lambdas.yml)}
resources:
  - Resources:
      ${file(serverless/resources/iam.yml)}
  - Resources:
      ${file(serverless/resources/policies.yml)}
plugins:
  - serverless-webpack