ioTProvisionByClaimRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: IoTProvisionByClaimRole
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: iot.amazonaws.com
          Action: 'sts:AssumeRole'
    ManagedPolicyArns:
      - Fn::Join: [ ":", [ "arn", 'aws', "iam:", 'aws', "policy/service-role/AWSIoTThingsRegistration" ] ]